#!/usr/bin/env bash
echo "prepare dist/ directory ... "
rm -rf dist/
mkdir -p dist
echo "build src/* -> dist/modules/ ..."
./node_modules/.bin/lsc -o dist/modules/ -cb src/*.ls
echo "bundle js files to dist/plotdb.js ... "
cat dist/modules/main.js \
    dist/modules/type.js \
    dist/modules/chart.js \
    dist/modules/theme.js \
    dist/modules/data.js \
    dist/modules/config.js \
    dist/modules/util.js \
    dist/modules/view.js > dist/plotdb.js

echo "build src/plotdb.styl -> dist/plotdb.css"
./node_modules/.bin/stylus -p src/plotdb.styl > dist/plotdb.css

echo "minifying plotdb.js ..."
./node_modules/.bin/uglifyjs dist/plotdb.js > dist/plotdb.min.js
echo "minifying plotdb.css ..."
./node_modules/.bin/uglifycss dist/plotdb.css > dist/plotdb.min.css
echo "remove dist/modules/ ... "
rm -rf dist/modules/
echo "deploy into local web ..."
mkdir -p web/static/assets/lib/plotdb
cp -R dist/* web/static/assets/lib/plotdb
echo "done."

